### 엘라스틱 서치 기본 검색 템플릿
GET http://localhost:9200/_search
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

### 인덱스 삽입
PUT http://localhost:9200/article_filtered_stream
Content-Type: application/json

{
  "settings": {
    "analysis": {
      "analyzer": {
        "korean": {
          "type": "custom",
          "tokenizer": "nori_tokenizer"
        },
        "edge_ngram_analyzer": {
          "type": "custom",
          "tokenizer": "edge_ngram_tokenizer",
          "filter": ["lowercase"]
        }
      },
      "tokenizer": {
        "edge_ngram_tokenizer": {
          "type": "edge_ngram",
          "min_gram": 1,
          "max_gram": 20,
          "token_chars": ["letter", "digit"]
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "ID": {
        "type": "long"
      },
      "STATUS": {
        "type": "keyword"
      },
      "TITLE": {
        "type": "text",
        "analyzer": "korean",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          },
          "ngram": {
            "type": "text",
            "analyzer": "edge_ngram_analyzer"
          }
        }
      },
      "CONTENTS": {
        "type": "text",
        "analyzer": "korean",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          },
          "ngram": {
            "type": "text",
            "analyzer": "edge_ngram_analyzer"
          }
        }
      }
    }
  }
}


### 단건 삽입
POST http://localhost:9200/article_filtered_stream/_doc/367289438580768
Content-Type: application/json

{
  "ID": 367289438580768,
  "STATUS": "DRAFT",
  "TITLE": "한글 테스트",
  "CONTENTS": "한글 테스트 컨텐츠"
}

### 타입 명시 후 단건 검색
GET http://localhost:9200/article_filtered_stream/_doc/367289438580768
Content-Type: application/json

### 쿼리 검색
GET http://localhost:9200/article_filtered_stream/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "CONTENTS": "한글"
    }
  }
}


### 단건 삭제
DELETE http://localhost:9200/article_filtered_stream/_doc/367289438580768
Content-Type: application/json

### 인덱스 매핑 확인
GET http://localhost:9200/article_filtered_stream/_mapping


### 인덱스 전체 삭제
DELETE http://localhost:9200/article_filtered_stream
Content-Type: application/json


### 인덱스 생성 테스트
PUT http://localhost:9200/index_test?pretty
Content-Type: application/json

### 비멱등성 일반 post 방식
POST http://localhost:9200/index_test/_doc
Content-Type: application/json

{
  "title": "test",
  "content": "test",
  "rating": 7
}


### 문서 생성 / 전체 수정 - id 를 명시하여 멱등성이 유지되는 멱등성 post 방식 - 사실상 put이랑 동일하게 동작하게 설계해둠
POST http://localhost:9200/index_test/_doc/1
Content-Type: application/json

{
  "title": "test",
  "content": "test"
}


### 생성 문서 조회
GET http://localhost:9200/index_test/_search


### 문서 수정 - restful put 으로 replace
PUT http://localhost:9200/index_test/_doc/1?pretty
Content-Type: application/json

{
  "content": "test2"
}


### 문서 부분 수정
POST http://localhost:9200/index_test/_update/1
Content-Type: application/json

{
  "doc": {
    "content": "test3"
  }
}



### 검색
### 검색어가 포함된 문서 검색
GET http://localhost:9200/index_test/_search?q=test


### 필터로
GET http://localhost:55575/index_test/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": {
        "match": {
          "content": "test"
        }
      },
      "filter": {
        "range": {
          "rating": {
            "gte": 7
          }
        }
      }
    }
  }
}


### 토크나이징 확인하기
POST http://localhost:55575/_analyze
Content-Type: application/json

{
  "analyzer": "standard",
  "text": "한글의 경우는 어떻게 토크나이징되는지 한번 보자"
}

### 한글 토크나이징 형태소 분석기 써보기
POST http://localhost:55575/_analyze
Content-Type: application/json

{
  "analyzer": "nori",
  "text": "한글의 경우는 어떻게 Tokenizing 되는지 한번 보자"
}

### article_filtered_stream 아날라이저 확인 - 한글 형태소 분석기 + 엣지 ngram 으로 튜닝해둔상태
POST http://localhost:55575/article_filtered_stream/_analyze
Content-Type: application/json

{
  "analyzer": "edge_ngram_analyzer",
  "text": "한글의 경우는 어떻게 Tokenizing 되는지 한번 보자"
}

### 아날라이저 구성요소 보기
GET http://localhost:55575/article_filtered_stream/_settings
#
#        "analysis": {
#          "analyzer": {
#            "korean": { (아날라이저 1, 형태소 아날라이저)
#              "type": "custom",
#              "tokenizer": "nori_tokenizer"
#            },
#            "edge_ngram_analyzer": { (아날라이저 2, 엣지 ngram 아날라이저)
#              "filter": [
#                "lowercase"
#              ],
#              "type": "custom",
#              "tokenizer": "edge_ngram_tokenizer"
#            }
#          },
#          "tokenizer": {
#            "edge_ngram_tokenizer": {
#              "token_chars": [
#                "letter",
#                "digit"
#              ],
#              "min_gram": "1",
#              "type": "edge_ngram",
#              "max_gram": "20"
#            }
#          }
#        }


### 테스트 데이터
POST http://localhost:45321/test/add


### api test - 기본 키워드 검색
GET http://localhost:45321/test/search2?keyword=잘되나



###
GET http://localhost:9200/article_filtered_stream/_search
Content-Type: application/json

{
  "query": {
    "bool": {
      "must": [
        { "match": { "TITLE": "잘되나" } },
        { "match": { "CONTENTS": "잘되나" } }
      ],
      "filter": {
        "term": {
          "STATUS": "DRAFT"
        }
      }
    }
  }
}